source 'https://rubygems.org'

gem 'jekyll',        '~> 3.3.1'
gem 'jekyll-assets', '~> 2.2.8'
gem 'pygments.rb',   '~> 0.6.3'
gem 'coffee-script', '~> 2.4.1'
gem 'sass',          '~> 3.4.22'
gem 'font-awesome-sass', '~> 4.7'
gem 'uglifier',      '~> 3.0.3'
gem 'bourbon',       '~> 4.2.7'
gem 'static_deploy', '0.2.0'
gem 'rake'
