source 'https://rubygems.org'

gem 'jekyll',        '~> 3.6.2'
gem 'jekyll-assets', '~> 2.4.0'
gem 'pygments.rb',   '~> 1.2.0'
gem 'coffee-script', '~> 2.4.1'
gem 'sass',          '~> 3.5.2'
gem 'bourbon',       '~> 4.2.7'
gem 'font-awesome-sass', '~> 4.7'
gem 'uglifier',      '~> 3.0.3'
gem 'static_deploy', '0.2.0'
gem 'rake'
